"""add eCNS280

Revision ID: 238ce21d1fb4
Revises: 
Create Date: 2017-12-04 21:10:27.432943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238ce21d1fb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecns280s',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tsn_ip', sa.String(length=32), nullable=True),
    sa.Column('tsn_username', sa.String(length=64), nullable=True),
    sa.Column('tsn_password', sa.String(length=64), nullable=True),
    sa.Column('usn_ip', sa.String(length=32), nullable=True),
    sa.Column('usn_username', sa.String(length=64), nullable=True),
    sa.Column('usn_password', sa.String(length=64), nullable=True),
    sa.Column('ugw_ip', sa.String(length=32), nullable=True),
    sa.Column('ugw_username', sa.String(length=64), nullable=True),
    sa.Column('ugw_ip_password', sa.String(length=64), nullable=True),
    sa.Column('usage', sa.String(length=32), nullable=True),
    sa.Column('pc_ip', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tsn_ip'),
    sa.UniqueConstraint('ugw_ip'),
    sa.UniqueConstraint('usn_ip')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ecns280s')
    # ### end Alembic commands ###
