"""add enb id

Revision ID: 62e43ac5f133
Revises: 
Create Date: 2017-11-13 22:13:29.366446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e43ac5f133'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enbs', sa.Column('enb_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enbs', 'enb_id')
    # ### end Alembic commands ###
