"""add board mode for enb

Revision ID: e7c938f486e1
Revises: 62e43ac5f133
Create Date: 2017-11-14 23:12:42.197765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c938f486e1'
down_revision = '62e43ac5f133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_model', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_model')
    )
    op.add_column(u'enbs', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'enbs', 'boards', ['board_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enbs', type_='foreignkey')
    op.drop_column(u'enbs', 'board_id')
    op.drop_table('boards')
    # ### end Alembic commands ###
